### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by esserdaniel** [tom-englert/RegionToShare#14]
**Important**
Read https://github.com/dotnet/ResXResourceManager/blob/master/Documentation/Topics/Troubleshooting.md first.
Problems listed there are bugs in Visual Studio and should be reported to Microsoft, not here.

**Describe the bug**
Does not work at all. Flickering. Does not share the content within the Windows

**To Reproduce**
Use it.

**Expected behavior**
Shoud Work

**Comment by esserdaniel** [comment]
[](url

https://user-images.githubusercontent.com/7695350/153710497-642d85ec-3c9a-4ad9-b8e6-74a50b5d4357.mp4

)

**Comment by tom-englert** [comment]
What OS? Which tool used to share?
What is expected to be seen on the video?

**Comment by tom-englert** [comment]
No feedback, closed as stale
