### ISSUE TITLE
Add menu to select standard desktop sizes

### ISSUE THREAD

**Issue by neilsleightholm-paxton** [tom-englert/RegionToShare#27]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think it would be useful to be able to quickly configure standard desktop sizes, e.g. 1027.x768, 1920×1080, 1366×768, from a right click menu on the main window or the control menu.

**Describe alternatives you've considered**
Looked at using PowerToys and there have been discussions about the function of RegionToShare to PowerToys but these where rejected.

**Additional context**
None.

**Comment by neilsleightholm-paxton** [comment]
Duplicate of https://github.com/tom-englert/RegionToShare/issues/33

**Comment by tom-englert** [comment]
Closed as duplicate
