### ISSUE TITLE
Mac equivalent

### ISSUE THREAD

**Issue by david-808** [tom-englert/RegionToShare#3]
Stumbled upon this utility, but my setup is using a Mac. Is there an equivalent program, or can this be ported for Mac?

**Comment by tom-englert** [comment]
Maybe some experienced Mac-developer could do this - but not me... 😞

**Comment by tconroy** [comment]
Here is a mac equivalent, however sadly not open source: https://apps.apple.com/de/app/advanced-screen-share/id1597458111
