### ISSUE TITLE
Config or settings-menu to choose theresolution/aspect ratio of the window

### ISSUE THREAD

**Issue by Shamatix** [tom-englert/RegionToShare#33]
Hi there,

 First of all I want to say this tool looks amazing! I cant wait to try it further.
I havn't been able to find any form of config file, or settings menu where I can type in the dimensions I want?

Such as resolution 1920x1080 aspect ratio 16:9, which would be really damn cool.
Perhaps even save em to some form of "Presets", but this part deffinetly isn't nessesary, however it would make so much sense to be able to set the resolution / aspect ratio.

Best regards

**Comment by rutgersmit** [comment]
I've submitted a pull request for this feature #32

**Comment by benabraham** [comment]
@tom-englert could you merge the pull request? Pretty please.
