### ISSUE TITLE
Incorrect pixel resolution

### ISSUE THREAD

**Issue by esbjornlarsen** [tom-englert/RegionToShare#34]
**Environment**
- Operating System: (Win11 beta 22621.1)

**Describe the bug**
The pixel size is reporting incorrect resolution before window is actively sharing and resizes resolution after pressing play button to actively share.

**To Reproduce**
When sizing the region to share window to exactly 1920x1080 the pixel in the lower right corner reports 1934x1087. This is before pressing the play button to make the window active to share. I know this because when using SnagIt to make a screen capture of the window, the captured pixel size is exactly 1920x1080. After pressing play button to make the window actively sharing information and making another SnagIt screen capture, the captured pixel size is 1929x1089. The actual size of the shared information of the window is 1924x1085. Hence, even when setting up the window to a preferred exact sharing resolution, when pressing play to activate the window the resolution has now changed and hence not a perfect sitation when you want to share an exact resolution. This is expecially important for Teams/Zoom meetings that are recorded. Being a few pixels off when sharing can be at best annoying and at worst crucial depending on what you're sharing. LOVE THE PRODUCT but needs some fine-tuning.

**Expected behavior**
The pixel resolution is expected to report correct resolution when sizing up the window and stay at the exact same resolution after pressing play to actively share content inside the window.

**Comment by benabraham** [comment]
If I want to share exactly 1920×1080 the opaque window needs to show 1926×1084 and the frame is 1928×1100 (+8 and +20 pixels)

![image](https://user-images.githubusercontent.com/334494/183268350-b58fd8f6-4f52-471a-9741-baec59db0d86.png)
![image](https://user-images.githubusercontent.com/334494/183268399-d5329e1c-64f3-4750-a081-8160167e3f5a.png)

Windows 10 with modified font size settings so it probably affects the numbers
