### ISSUE TITLE
Other see blackscreen

### ISSUE THREAD

**Issue by icharge** [tom-englert/RegionToShare#36]
**Environment**
- Operating System: (Win10)
- Collaboration Tool: (MS Teams/ WebEx / Skype)

**Describe the bug**
Others in meeting see blackscreen. I'm using a corporative laptop.

**To Reproduce**
Pick RegionToShare window when sharing screen.

**Expected behavior**
It should working like Home PC.  I'm not sure that is something block screen rendering on the app?

**Comment by tom-englert** [comment]
It's hard to reproduce - I don't have access to your corporative laptop.

**Comment by tom-englert** [comment]
This is an open source project that comes free of charge - you can't expect getting individual support for free.
If it's a corporate device, maybe ask your IT to support you.

**Comment by icharge** [comment]
I just ask in case you wonder why this happened. Yes, I got it. I'll fix it by myself. Thanks for your time.
