### ISSUE TITLE
Shrink the size of the green frame top bar

### ISSUE THREAD

**Issue by JonathanPitre** [tom-englert/RegionToShare#37]
It would be great to shrink the size of the green frame top bar as it can hide information from the window under. 

![image](https://user-images.githubusercontent.com/15003329/177692074-5393c6a0-da23-41e3-9745-a0dae9c20b5b.png)

**Comment by tom-englert** [comment]
The green frame is not part of the shared region, so it's size does not matter. The shared region is only the region inside the green frame.
