### ISSUE TITLE
Following guide to region share displays black screen

### ISSUE THREAD

**Issue by sp-reach** [tom-englert/RegionToShare#39]
**Environment**
- Operating System: Win10
- Collaboration Tool: Teams

**Describe the bug**
A clear and concise description of what the bug is. (e.g. 'Does not work' is **not** a clear bug description.)
Sharing the "Region to share" window will show the green and black window to the user, but when I click that window to "play" or share what is inside that window a black screen appears to the user.  Furthermore if I then try to cancel screen share and re-share they report that the screen share of a black screen is still going and teams cannot start another screen share session.
![image](https://user-images.githubusercontent.com/80424905/184348174-19a3ea43-5238-452a-b222-6dd4033ba6ce.png)

Additionally when this bug occurs it crashes teams and I must task manager end it.

**To Reproduce**
Detailed steps to reproduce the behavior: (e.g. 'Use it' is **not** a detailed description.)
1. Start a teams call.
2. Share the "Region to share" window
3. Click inside the "Region to share" black and green window.
4. It shows on my (the sharers) screen ui is updated and it is sharing to the "outlined" screen, but the users watching only see a black screen.

**Expected behavior**
A clear and concise description of what you expected to happen. (e.g. 'Works' is **not** a clear description)
Sharing the "Region to share" window actually shares what is inside this window and doesn't freeze or cause a black screen.

**Comment by sp-reach** [comment]
UPDATE: The image in the bug is to show what window I'm sharing or whenever I reference "Region to share" window.

**Comment by sp-reach** [comment]
@dnkh Yes then the view changes as described above:

>  but when I click that window to "play" or share what is inside that window a black screen appears to the user.

**Comment by tom-englert** [comment]
> Additionally when this bug occurs it crashes teams and I must task manager end it.

Looks like the problem is on teams side

**Comment by sp-reach** [comment]
@tom-englert If this is true are are other users experiencing this?

**Comment by adam-wood** [comment]
This is anecdotal, but I have occasionally had problems (I use Teams). I once had a report of a black screen, or sometimes the shared content not showing the app I currently had under RegionToShare. In these instances, I simply stopped the share and re-shared (I may have also restarted RegionToShare, but don't recall. I don't recall the exact details however, and it has only affected me rarely.

**Comment by sp-reach** [comment]
I've tried re-starting ReginToShare multiple times and restarting teams. The one thing I've yet to try is a PC restart.

**Comment by dnkh** [comment]
> @tom-englert If this is true are are other users experiencing this?

I'm also using Teams and have no issues on 3 different laptops ( 2x Windows 10, 1x Windows 11 )

**Comment by tom-englert** [comment]
Some of my colleagues sometimes have the same problem even without RTS

**Comment by sp-reach** [comment]
Update this has been resolved since a windows restart. Unsure if that is one of the setup requirements.
