### ISSUE TITLE
Region of secondary monitor not shareable

### ISSUE THREAD

**Issue by PHaumering** [tom-englert/RegionToShare#41]
**Environment**
- Operating System: Win10
- Collaboration Tool: none/MSTeams

**Describe the bug**
If I prepare the region on my secondary monitor and click the play button to activate the region, the actually shared region will be a small rectangle in the top left corner of my primary monitor. 

Additionally, neither the taskbar nor windows in that region are actually shared if selected in MSTeams and only a black region is shared. However, moving the mouse into that region results in it being shared correctly.

**To Reproduce**
1. Prepare a 2 monitor setup where the second monitor extends the desktop
2. Start RegionToShare
3. Move window to a secondary monitor
4. Click play button to activate region to share

**Expected behavior**
RegionToShare works on my secondary monitor as well.

**Comment by PhantasmNZ** [comment]
Confirmed this behaviour as well.  If you hit "play" on the primary monitor then you can drag to a secondary - however this makes the really useful feature of being able to pause what you are sharing redundant.  I've also found it's not possible to pause or move  the "small rectangle" meaning you have to restart the app

**Comment by rzfzr** [comment]
Press the play button on the primary screen, then drag to the secondary and resize as needed, 
working well for me
