### ISSUE TITLE
Stop sharing button not visible when (unshared) window is positioned at top of display

### ISSUE THREAD

**Issue by ch-ey** [tom-englert/RegionToShare#46]
**Is your feature request related to a problem? Please describe.**
When the unshared RTS window is positioned at the top of the display and you then start sharing, the "close" button is not accessible because the top green border is offscreen now. (Resizing the RTS window would make it show up again, is this a bug?)

**Describe the solution you'd like**
As others have suggested already, some more right click options via the task bar would be helpful or an additional systray icon, or configurable "close" button location, ...

**Describe alternatives you've considered**
Create a zone (e.g. FancyZone) that does not extend to the top of the display and leaves space for the green border once sharing is enabled

**Additional context**
none

**Comment by tom-englert** [comment]
> Resizing the RTS window would make it show up again, is this a bug?
It's standard Windows behavior.

**Comment by tom-englert** [comment]
It's tricky to not interfere with multiple monitor requirements.

**Comment by tom-englert** [comment]
> Create a zone (e.g. FancyZone) that does not extend to the top of the display and leaves space for the green border once sharing is enabled

There is a simple workaround - just leave space for the Border.
