### ISSUE TITLE
Mouse pointer not visible. Google Meet under Chrome on Win11

### ISSUE THREAD

**Issue by APP32Piotr** [tom-englert/RegionToShare#48]
**Environment**
- Operating System: Win11
- Collaboration Tool: Google Meet under Chrome Browser

**Describe the bug**
Mouse pointer is not visible on the shared window.

I have seen that there has been a bug with double pointer shared ( #18 ). I have verified the version [1.0.4900](https://github.com/tom-englert/RegionToShare/releases/tag/1.0.4900) without the fix, and the cursor/pointer shows correctly. (other bugs from said version are of course present). This suggests that the fix broke my configuration somehow.

It seems that under Microsoft Edge the cursor is visible correctly.

**To Reproduce**
Open RegionToShare, click "play". Share the RegionToShare window using Google Meet. When the application underneath the RegionToShare window is active, the mouse pointer disappears.
But when I activate the RegionToShare application itself, the pointer shows up. It disappears again after clicking (and activating the underneath window again)

**Expected behavior**
The mouse pointer should be visible on the shared RegionToShare when the underneath application is active.

**Comment by tom-englert** [comment]
Since that works fine in all other sharing apps, it is rather an issue of Google Meet
