### ISSUE TITLE
Teams freezes when using Region to Share

### ISSUE THREAD

**Issue by tarunganga** [tom-englert/RegionToShare#50]
**Environment**
- Operating System: (Win10)
- Collaboration Tool: (Teams)

**Describe the bug**
When i try to share part of my 49" screen using Region to Share, Teams Freezes. I'm sharing my screen when I'm in a call or a meeting (Obviously) during which i cannot even end the Teams calls. Screen share is stuck and Teams is stuck.

**To Reproduce**
Start region to share after teams call has started and share your region to share window

**Expected behavior**
It is expected that teams is not stuck and i'm able to share my screen with this amazing tool

**Comment by tom-englert** [comment]
If Teams get stuck it is an issue of Teams - RTS is agnostic of the sharing app.

**Comment by tom-englert** [comment]
I once had issues when selecting the RTS window in Teams before switching it to active mode, but it worked fine when it was already active - maybe that helps

**Comment by tarunganga** [comment]
Ah so you would suggest me to have RTS window active before i start a call ?

**Comment by tarunganga** [comment]
I think we can close this. I was not able to reproduce the issue after a couple of days. So, i agree that its a teams issue
