### ISSUE TITLE
No certificate found with the supplied thumbprint

### ISSUE THREAD

**Issue by larrywa** [tom-englert/RegionToShare#51]
**Environment**
- Operating System: (Win11)
- Collaboration Tool: (Teams)

**Describe the bug**
In Visual Studio 2022, I am receiving this error"No certificate found with the supplied thumbprint: B41FC1839075876CFB8F3D4B9DAA420CA6DEB431"

**To Reproduce**
Load the project in Visual Studio 2022, try to build

**Expected behavior**
I'm not sure I was expecting to have a certificate. If I need one, just explain what I need to do.

**Comment by tom-englert** [comment]
Just don't build the package
