### ISSUE TITLE
Custom Background Picture or Color

### ISSUE THREAD

**Issue by Knochi** [tom-englert/RegionToShare#53]
**Is your feature request related to a problem? Please describe.**
When not using the whole area a green striped background is displayed

**Describe the solution you'd like**
Have an option to configure the background pattern and color or insert custom picture (scaling/ratio then might be difficult)

**Describe alternatives you've considered**
combine with fancy zones from Microsoft Power Toys to always use the same space and size

**Additional context**
background picture might just take the desktops wallpaper and resize

**Comment by tom-englert** [comment]
The latest version does not show a green background, and the color is customizable, maybe try to update first?

**Comment by Knochi** [comment]
I have version [1.3.5651 ](https://github.com/tom-englert/RegionToShare/releases/tag/1.3)
This is what my colleague sees ![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/5979046/229078609-d7107e91-303e-4bb2-b6db-9bd93c3539e6.png)

**Comment by tom-englert** [comment]
The latest version in the store is 1.5

**Comment by tom-englert** [comment]
OK, there seems to be something wrong in the store, it says V1.5, but looks like 1.3. Can you try the latest release from here?

**Comment by Knochi** [comment]
i did use the binary from releases section of this page
