### ISSUE TITLE
Switching between Multiple virtual desktops

### ISSUE THREAD

**Issue by pontusbredin** [tom-englert/RegionToShare#54]
Hi, thank you for this very nice piece of software!

If I start RegionToShare on the first Desktop and share it in Teams all is good. If I then switch to another desktop Ctrl+Win+LeftArrow RegionToShare still shares the first desktop. This was not the case before and it might be because Microsoft changed something in Windows 11.

It would be very nice to have this functionality back as it makes sharing multiple different screens very easy.

Best regards

**Comment by tom-englert** [comment]
RTS is agnostic of desktops or windows version. If Windows has changed it's behavior, there is nothing much we can do here - you will probably have to move RTS to the new desktop, to share the content from there.

**Comment by swissarmykirpan** [comment]
@pontusbredin you can set the RegionToShare App to be available on all Virtual Desktops.

Win + Tab to show up the Multiple Desktops panel also showing windows of the current desktop. Right click on one of them and you can choose either "Show this window on all desktops" or "Show windows from this app on all desktops"
