### ISSUE TITLE
Resolution on secondary monitor

### ISSUE THREAD

**Issue by tdx79** [tom-englert/RegionToShare#57]
**Environment**
- Operating System: Win10
- Collaboration Tool: Teams / Windows (issue seen also testing the app in desktop)
- Monitors: LG 5K2K (res. 5120x2160, scale and layout 125%) + LG 4K (res. 3840x2160, scale and layout 150%)

**Describe the bug**
Selected resolution of shared area is not being kept when moving the app to secondary monitor (or sharing from secondary monitor)

**To Reproduce**
Open the "Region to Share" app from main monitor, set the shared area resolution to 1920x1080. Drag the app window to secondary monitor, the shared area resolution changes to 2304x1296.

**Expected behavior**
When moving the shared area between monitor, shared area resolution should not change

**Comment by tom-englert** [comment]
It keeps the pixel resolution, so moving between monitors with different resolutions will scale as described.
