### ISSUE TITLE
activated at start-up, not scaled so no way to stop

### ISSUE THREAD

**Issue by jerry-sileon** [tom-englert/RegionToShare#58]
**Environment**
Operating System: (Win10/Win11)

**Describe the bug**
I installed RegionToShare from the Windows Store. My setup is a 4K laptop screen (scaled down to be able to read anything) plus two external 1900x1200 displays (or, at home, a single 4K screen scaled 1:1).

When I start the app, I see a program icon in the taskbar and a dashed border over my active window with a little margin to the top and to the left. There is no large play button in sight as I see on the examples, no title bar as if the region is already active. (When I start to share a window, Teams already shows it as an active window.)

The taskbar icon does not have a right-click menu and I see nothing about shortcut keys to start/stop the RegionToShare.

So I am having a few problems:
- RegionToShare activated at start-up
- window not scaled on a scaled display
- X button to deactivate out of sight
- no shortcut keys

I hope there is a simple solution to my problems because with a large monitor it is a very useful piece of software!

**Comment by tom-englert** [comment]
Drag the window using the dashed border until the x in the top right corner comes into sight, then you can close the window.

**Comment by tom-englert** [comment]
Drag the window using the dashed border until the x in the top right corner comes into sight, then

**Comment by tom-englert** [comment]
An do not start activated if it causes trouble

**Comment by jerry-sileon** [comment]
Oh, I tried move the window by dragging the dashed border but couldn't do it, now it seems to work. The difference is that now I have a 4K monitor to the right of my 4K laptop screen (laptop scaled, monitor not scaled). Now I see the Close box on the monitor as well.
I was wondering about start acitvated, but could not find a way to set that. Now I can finally resize the window and actually stop it, now I see the Start activated checkbox. Perhaps a startup parameter for people with the same problem?

Thanks, I can finally use it! :)
