### ISSUE TITLE
remember last position and size

### ISSUE THREAD

**Issue by harrybin** [tom-englert/RegionToShare#59]
Please remember position and size.

I use the Windows 11 snap windows feature to get size like:
![image](https://github.com/tom-englert/RegionToShare/assets/15869006/3626c857-5fed-43db-b349-7755139ac606)
This causes the resolution 1721x1039 and positioning at the top left of the monitor as expected.

Then when closing RTS and opening again it falls back to 1699x1024 resolution and a postion the window had before the using windows 11 snap window feature.

I'm using the latest version  v1.6.5717

**Comment by tom-englert** [comment]
I can't reproduce, however I don't have Win11. Can you try to debug this?

**Comment by tom-englert** [comment]
It remembers size and position, so without further information there is nothing I can do here.
