### ISSUE TITLE
Does not seem to work in WebEx

### ISSUE THREAD

**Issue by AaronCompNetSys** [tom-englert/RegionToShare#6]
The outstanding issue where WebEx adds the white bars to the outside of the masked region, still affects how recipient of your meeting see your shared section. I think this is a bug in WebEx not your tool, because it happens exactly the same inside its own app when you try to share just a window.

Unless you have an idea for how to correct this such as emulating a monitor, please just update your main page to let WebEx users know your app might not help them.

**Comment by tom-englert** [comment]
Could not reproduce, however according to the description it looks more like a WebEx issue.
