### ISSUE TITLE
Resizes when DPI on second monitor doesn't match primary

### ISSUE THREAD

**Issue by BarrieSharp** [tom-englert/RegionToShare#60]
**Environment**
- Operating System: Win11

**Describe the bug**
When using multiple displays with different DPI scaling, the app resizes after pressing play on a secondary display based on the factor between the two. 

**To Reproduce**
- Using two displays, set the primary to 150% and the secondary to 100% DPI.
- In its paused state, drag Region to Share to the secondary display and resize to fill only a portion of the screen.
- After pressing play, the captured area will reduce by the difference between DPIs.
- Pause again and make the secondary the primary.
- Repeating the steps now has an inverse result with the region becoming bigger on the secondary screen. Note that this can mean you don't have access to the close button to pause the app as the window may end up bigger than the screen.
- 

**Expected behaviour**
- The app should not resize its region when different DPIs are used.
- A guard should be in place to stop the app becoming larger than the screen it is on and getting stuck because the user can interact with the window.
- Maybe a right-click option on the task bar icon to maximise.

**Comment by tom-englert** [comment]
I can't reproduce, which version are you using?

**Comment by BarrieSharp** [comment]
1.7.5879.0 installed from Microsoft Store.

**Comment by tom-englert** [comment]
It resizes when I move it, like any other window, but not when I click start

LG
Tom
________________________________

**Comment by BarrieSharp** [comment]
I have added a quick capture to demonstrate the behaviour. Have you set each screen to use different DPI scaling?
![ResizeExample](https://github.com/tom-englert/RegionToShare/assets/11975682/9dc09647-4970-4cf7-b73c-f55c7e654d29)

**Comment by tom-englert** [comment]
I have no clue how you do this. 
However this is a very rare edge case any how, so feel free to debug into this and provide a fix.

**Comment by BarrieSharp** [comment]
Fair enough. I will give it a try. I don't know how wpf works with DPI scaling so I might learn something.

**Comment by crashkonijn** [comment]
@BarrieSharp already had time to dive into this? I'm having the exact same issue.

**Comment by BarrieSharp** [comment]
I'm hoping to get a moment on this in the holidays. I have looked through the code to get familiar with what is happening. The app is DPI aware but it may not get updated when it changes screens. It's using Windows libraries so hard to know what's happening in the background. I plan to run in debug and watch the numbers at each step to see where the scaling applies. Then it's a question of how to correct. I imagine you can get the DPI of the current screen. I don't want to apply a scale if I can get it to return the correct value. Maybe DPI awareness should be removed from the config.

**Comment by tom-englert** [comment]
Should be fixed in 1.10

**Comment by crashkonijn** [comment]
That's amazing, thank you!

**Comment by BarrieSharp** [comment]
I have checked with my screens and the issue appears to be resolved. Great work and thank you.

Is the update be available on the MS Store?

**Comment by tom-englert** [comment]
> Is the update be available on the MS Store?
Submission is done, will take a few days until it is validated and active.
