### ISSUE TITLE
Intergrate into FancyZones in MS PowerToys

### ISSUE THREAD

**Issue by asjones987** [tom-englert/RegionToShare#61]
There are already people using RegionToShare and MS PowerToys FancyZone together for screen sharing of wide monitors. Integrating the two would be a very nice feature

Example of those using the two together.
https://www.reddit.com/r/MicrosoftTeams/comments/u28mec/ultrawide_share_region_of_screen/

Related issues on the PowerToys Side:
https://github.com/microsoft/PowerToys/issues/25179
https://github.com/microsoft/PowerToys/issues/2774
https://github.com/microsoft/PowerToys/issues/279

**Comment by tom-englert** [comment]
I can't integrate FancyZones into RegionToShare, someone needs to integrate RegionToShare into FancyZones.
