### ISSUE TITLE
Region expands on single monitor setup past after dragging into Fancy Zone region

### ISSUE THREAD

**Issue by ty-watkins** [tom-englert/RegionToShare#62]
**Environment**
Windows 11
MS Teams

**Describe the bug**
Using Fancy Zones in combination with region to share on my 4K 32" monitor. DPI is set to 125% scaling. When I drag it into a region set by Fancy Zones, the resolution that Region to Share gets set to is larger than the area that Fancy Zones has. When you activate the region to share, it expands past the zone boundary and any window/app I place in the Fancy Zone has gaps that people can see through to the applications or desktop behind it.

My Fancy Zone area is set to 1536x1094. Fancy Zones is DPI aware and this is the scaled resolution. The actual pixel/monitor resolution of this area is 1920x1368. Region to Share gets set to 1940x1377 when it is snapped into the same region.

**To Reproduce**
Have Fancy Zones configured and running. Drag Region to Share window to a zone and activate. (You can see the region expand past the boundary here even before trying to use it with MS Teams). Share window from MS Teams. Drag web browser or other application into the region. Shared screen is larger than the snapped application and other people on the call can see behind the application on the edges.

**Expected behavior**
Region to Share should be able to detect and correctly set the same resolution that it's currently occupying and that is also set by the Fancy Zones area. 

My Fancy Zone area is set to 1536x1094. Fancy Zones is DPI aware and this is the scaled resolution. The actual pixel/monitor resolution of this area is 1920x1368. Region to Share gets set to 1940x1377 when it is snapped into the same region. I would expect it to have matched the 1920x1368 resolution. When activated the Region to Share expands past the current window size to match it's setting.

I've attached a screenshot (hopefully it's attached correctly!) Showing that there is a mismatch between the application snapped into the Fancy Zone and what Region to Share is showing after activating.

![Screenshot 2023-08-23 180851](https://github.com/tom-englert/RegionToShare/assets/115261409/ebec7911-410b-43ad-affa-c3874ae7e426)

**Comment by tom-englert** [comment]
The mainly because of the glass frame around the window - Fancy Zones seems to substract that glass fame size from the 
physical windows size.

**Comment by ty-watkins** [comment]
I have my two zone at exactly half the screen and I've set the space between the zones to 0. I just check and the discrepancy happens even when using Windows Snap to half screen. Region to share gets set to 1936x2108. Half the width of a 4k screen should be 1920.

**Comment by ty-watkins** [comment]
Also, when you full screen Region to share, the pixel width gets set to 3858 which is 18 more pixels than my 4k monitor resolution of 3840.
