### ISSUE TITLE
High Processor and Memory Consumption

### ISSUE THREAD

**Issue by brianritzi** [tom-englert/RegionToShare#67]
**Environment**
- Operating System: Win11 11th Gen Intel Core i5-1145G7G7 @ 2.60GHz 1498 Mhz, 4 Cores, 8 Logical Processors
- 16 GB Memory
- Collaboration Tool: Teams or none

**Describe the bug**
 The app is using an excessive amount of resources (process and memory consumption) and causing delays and stutters when performing typical computing tasks (moving windows, typing, moving mouse pointer) at the same time as running the app. It only happens when running the app. Does not happen when app is just open but not running/sharing a region. It happens with or without running Teams or any other collab tool. 

**To Reproduce**
Start and then run the app to share a region of the screen. Then do anything else.

**Expected behavior**
No stuttering or slowing down of the operating system and other apps.

See attached Process Monitor Screenshot
![Region To Share - resource usage 11-20-2023](https://github.com/tom-englert/RegionToShare/assets/151538657/87da9da2-6b84-492e-b186-a525a7a45dee)

**Comment by tom-englert** [comment]
This is by design, I think there is nothing much to improve. 
What you can do is:
- reduce the size of the shared region, a lager region will require more memory and CPU
- reduce the frame rate:
![image](https://github.com/tom-englert/RegionToShare/assets/10229954/72a3bca0-e542-4213-9088-e4f8874cf958)

**Comment by brianritzi** [comment]
Thanks Tom. I will try these options. Thanks for the quick response, and
for creating such a helpful app.

~Brian
