### ISSUE TITLE
Doesn't Display Content

### ISSUE THREAD

**Issue by guyrleech** [tom-englert/RegionToShare#68]
**Environment**
Win11 22H2 ARM
Zoom

**Describe the bug**
The Region to Share window is seen but no local Window dragged over the top is seen in the remote session.

**To Reproduce**
Start meeting
Share Region to Share Window
Drag any window over Region to Share (RtS) Window
That window is not shown in the remote session, it continues to show the empty RtS window and the chosen background, solid of that window.

**Expected behavior**
The window dragged over the local RtS window should be displayed in the remote Zoom session as it has previously

**Comment by tom-englert** [comment]
Did you try to click on the background while RTS is in active mode?

**Comment by guyrleech** [comment]
I've not done anything different to last time AFAIK but it's now working so apologies. Please mark as resolved - PEBCAK

**Comment by guyrleech** [comment]
User error it would seem

**Comment by tom-englert** [comment]
Sometimes the sharing application messes up the z-order of the windows, and clicking with the mouse will fix it.
