### ISSUE TITLE
Allow autostore last window sizes/positions

### ISSUE THREAD

**Issue by larsilus** [tom-englert/RegionToShare#69]
**Is your feature request related to a problem? Please describe.**
I have a Laptop Screen, showing my outlook window mostly, and a connected wide monitor which is quite large, where i have a fullscreen citrix deskop window, where my clients works ist. i only want to show my meeting colleagues a defined part of the big screen (half the citrix window, otherwise too big). But when closing RegionToShare after usage und reuse it later or after windows restart i always need to resize the window to the exact same dimensions i like. it's annoying because it always want to have the same part of my screen replicated and i dont like to do it again and again every time.

**Describe the solution you'd like**
Please allow to store (or best store automatically) the last window sizes/positions, so even after restart of the app, i (best automatically) get the same last window already prepared and perfectly placed and sized

**Describe alternatives you've considered**
dont think, there is an alternative

**Additional context**
please ask me if problem is not clearly described.
I really like this app, it saves me a lot of frustation because otherwise in my usecase i would always need to move the citrix wide screen window to my small laptop screen, and this scrambles all my window alignments inside the citrix desktop.

**Comment by larsilus** [comment]
Did a small donation for motivation 8) thanks for your hard work

**Comment by larsilus** [comment]
Hi, thanks for tyring to fix this.
I used the current version from microsoft store, 1.9.6146.0, still the same issue.
Inititially it opens with 300x200, then i resize to a larger part, then close the app, and start it again via taskbar.
reopens in 300x200 again.

**Comment by tom-englert** [comment]
The settings are saved in a path like this, is the "WindowPlacement" stored as expected?
C:\Users\englertt\AppData\Local\Packages\15863TomEnglert.RegionToShare_c1sj353grjxmm\LocalCache\Local\tom-englert.de\RegionToShare.exe_Url_azezbdf0zzr2zvw4lvdo2yozmtiphryg\1.9.6146.0

When you start non-activated, is it still the same issue?

**Comment by tom-englert** [comment]
I think this was related to #60
