### ISSUE TITLE
Show context menus

### ISSUE THREAD

**Issue by GeorgHohenberger** [tom-englert/RegionToShare#73]
When sharing a application with Teams all context menus are not shown (Mabe because these are other windows of this application?!?).
Therefore I normally share my screen as i want to show context menus and drop down lists ect.

Equally when using RegionToShare context menus in the region are not shown. Please show them or make it a setting to show them.

Thank you

**Comment by tom-englert** [comment]
I can't reproduce this, are you sure you are sharing the RTS window?

**Comment by tom-englert** [comment]
No feedback, closed as stale
