### ISSUE TITLE
Integrate with Microsoft PowerToys

### ISSUE THREAD

**Issue by QuickScoP3s** [tom-englert/RegionToShare#74]
Would be awesome if you could integrate this as a PowerToys:
https://github.com/microsoft/PowerToys

They already have their "Fancy Zones", but being able to share a zone would be amazing 💪

Maybe you could help with this ticket:
https://github.com/microsoft/PowerToys/issues/2774

**Comment by tom-englert** [comment]
Duplicate of #61
