### ISSUE TITLE
Option to remove green border

### ISSUE THREAD

**Issue by Wraithstalker90** [tom-englert/RegionToShare#75]
**Is your feature request related to a problem? Please describe.**
I am trying to share screen on a 32:9 monitor and i would like to be able to stream a 16:9 portion but not have to see the green lines on the sides.

**Describe the solution you'd like**
option to remove the green outlines on the sides when activated.

**Describe alternatives you've considered**
option to make the lines 1 pixel wide if unable to hide them completely.

**Comment by tom-englert** [comment]
How would you then know what region you are sharing?

**Comment by tom-englert** [comment]
BTW the default color is slate blue, not green - maybe you are using a totally outdated version?

**Comment by Wraithstalker90** [comment]
you are right it is blue, i had closed out when i was writing the first message and thought it was green. At least for my use case i always stream the exact same portion of my screen so once i start streaming i don't need/want the border distracting me from the full screen content.

**Comment by tom-englert** [comment]
Did you try setting the color to transparent?

**Comment by Wraithstalker90** [comment]
i didn't realize that was an option, it's just what i wanted.
