### ISSUE TITLE
old version delivered via winget

### ISSUE THREAD

**Issue by abochmann** [tom-englert/RegionToShare#77]
**Environment**
- Operating System: (Win10)

**Describe the bug**
Region To Share is available for installation with [WinGet](https://github.com/microsoft/winget-cli), but it doesn't refer to the current version:

```
> winget show TomEnglert.RegionToShare
Found Region To Share [TomEnglert.RegionToShare]
Version: 1.6.5717
Publisher: Tom Englert
Publisher Url: https://github.com/tom-englert/RegionToShare
Publisher Support Url: https://github.com/tom-englert/RegionToShare/issues
Description: A Windows helper app to share only a part of a screen via video conference apps that only support either full screen or single window like e.g. Teams, WebEx, etc. This tool simply mirrors the content of a screen region into a hidden window. In your meeting app you then can just share the content of this hidden window.
Homepage: https://github.com/tom-englert/RegionToShare
License: GNU General Public License v3.0
License Url: https://github.com/tom-englert/RegionToShare/blob/main/LICENSE
Tags:
  teams
Installer:
  Installer Type: portable (zip)
  Installer Locale: en-US
  Installer Url: https://github.com/tom-englert/RegionToShare/releases/download/1.6/RegionToShare.zip
  Installer SHA256: 7ab940dd50eb1930ed07f003755eb11d1861a97879d71e0bfb40a21a231773a9
  Offline Distribution Supported: true

> winget install TomEnglert.RegionToShare
Found Region To Share [TomEnglert.RegionToShare] Version 1.6.5717
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/tom-englert/RegionToShare/releases/download/1.6/RegionToShare.zip
  ...   287 KB /  287 KB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Path environment variable modified; restart your shell to use the new value.
Command line alias added: "RegionToShare"
Successfully installed
```

I don't know who adds projects to winget, and who is then responsible for linking up releases, so possibly I need to raise the issue elsewhere?

**To Reproduce**
Install Region To Share with winget, ```winget install TomEnglert.RegionToShare```

**Expected behavior**
winget installs the current release

**Comment by abochmann** [comment]
Note: It seems the source for this version is winget, and I don't have access to the msstore source on this PC?

```
> winget search RegionToShare --source msstore
No package found matching input criteria.
> winget search RegionToShare --source winget
Name            Id                       Version
-------------------------------------------------
Region To Share TomEnglert.RegionToShare 1.6.5717
```

**Comment by tom-englert** [comment]
I never published this on WinGet.

If you can't access the store, you can download the binaries from the release page

**Comment by SamHasler** [comment]
@tom-englert in order to get the latest version on WinGet you would need to submit a PR to get this updated: https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TomEnglert/RegionToShare/1.6.5717

Would you be able to make that part of your release process?

**Comment by tom-englert** [comment]
Winget just unpacks the zip to a hidden folder, it does not provide any installation feature, so what is the benefit of it compared to just downloading the zip manually?

**Comment by SamHasler** [comment]
Having a single tool for discovering, installing and updating.

I can use `winget search <NAME>` to see if an app is available, `winget install <ID>` to install it,  `winget update` to see what installed tools have updates and `winget update <ID>` or `winget update --all` to update.
