### ISSUE TITLE
Program shouldn't open in active mode when first downloaded

### ISSUE THREAD

**Issue by WiscoKel** [tom-englert/RegionToShare#79]
**Environment**
- Operating System: Win10
- Collaboration Tool: N/A

**Describe the bug**
When initially downloading the program, it opened in the "active view". It opened with the button to close it off of the screen. I was able to change my primary monitor to be my larger one and close it. 

**To Reproduce**
Unfortunately I do not know how to replicate it as, once I fixed it, I haven't seen it happen again. Possibly by starting in active mode and not having multiple monitors or using a smaller monitor.

**Expected behavior**
When first downloading and opening the program, I would think starting in windowed mode would be better as you can use the Windows key plus arrows to move it on the monitor.

This could just be a "me" issue but thought it might be helpful to share in case others are seeing it.

**Comment by onguarde** [comment]
agree, took me some time to find that small close button.
