### ISSUE TITLE
Not available on Windows store

### ISSUE THREAD

**Issue by wasitacat** [tom-englert/RegionToShare#8]
Hi,

this tool looks to be great. However, it is not available for me in the microsoft store.

I am using this Windows-Version
    Edition	Windows 10 Home
    Version	21H2
    Betriebssystembuild	19044.1469
    Leistung	Windows Feature Experience Pack 120.2212.3920.0

I get an error saying that the product you are looking for is not available.
    Code: 0X00000005
    CV: wqIV8nl0BUSCTeiJ

Is there any way to build the tool myself if I install Visual Studio? Could you provide build instructions? Or maybe just a pre-built binary? Thanky you!

Best regards
Daniel

**Comment by tom-englert** [comment]
https://github.com/tom-englert/RegionToShare/releases
