### ISSUE TITLE
Windows on Arm version

### ISSUE THREAD

**Issue by t-h-e** [tom-englert/RegionToShare#80]
Is it possible to provide a native arm64 version of RTS?

I compiled RTS locally with a Snapdragon Elite X and everything seems to work as usual. Can you provide an arm64 release next to the x64 one?

Great tool by the way 😃

**Comment by tom-englert** [comment]
If you know all the plumbing needed to build and publish a single appx package for two platforms, you can provide a PR for this.

**Comment by t-h-e** [comment]
Can you have a look at https://github.com/tom-englert/RegionToShare/pull/81?
I am not sure if this is all that is needed, but so far it looks fine, expect that I could not test the *.appxbundle

**Comment by tom-englert** [comment]
none of the dependent packages is available as Arm64, so I wonder what would be the benefit of having half of the application Arm64 specific, while the rest is still AnyCPU.
