### ISSUE TITLE
Empty gray area in Teams

### ISSUE THREAD

**Issue by berk-steer73** [tom-englert/RegionToShare#82]
**Environment**
- Operating System: Win11
- Collaboration Tool: Teams

**Describe the bug**
When the play icon is pressed and the window is shared in Teams, it shows as a blank gray area for the attendees. The minimized Teams window for the host that shares their screen is shown below:
![image](https://github.com/user-attachments/assets/41433cd2-d359-4130-8a3a-1825eda6014c)

**To Reproduce**
1. Run Region to Share and click on the play icon.
2. Click on the "Share" button on Teams while in a meeting and share "Region to Share" window.
3. Observe that it's shown as a blank gray area.

**Expected behavior**
Instead of a blank gray area, the UI content in the shared region should be displayed.

**Comment by tom-englert** [comment]
Bugs in Teams must be reported to Microsoft, I can't do anything about this.

**Comment by berk-steer73** [comment]
@tom-englert , it's not a bug in Teams. Sharing other windows works fine. The problem happens only when sharing "Region to Share" window. I mean this application doesn't work with Teams due to the reason I have described in the issue description.

**Comment by tom-englert** [comment]
RTS does not interact with teams, it only provides a hidden window that replays the region
