### ISSUE TITLE
Doesn't work with the latest Teams

### ISSUE THREAD

**Issue by just1nchen** [tom-englert/RegionToShare#83]
**Environment**
- Operating System: Win11
- Collaboration Tool: Teams

**Describe the bug**
These days after Teams got upgraded to the latest version, seems like RegionToShare doesn't work now. 
When I click Share > Window > RegionToShare, the audiences can only see a white blank content, and then I stop the share, later when I re-try the share, I cannot share anymore (no matter share window or share screen).

**Comment by tom-englert** [comment]
RTS works exactly as before, it's Teams that is broken again.
You have to raise an issue for Teams.

**Comment by tom-englert** [comment]
Duplicate of #71
